- doc/cr.md
Signed-off-by: Sunyanan Choochotkaew <sunyanan.choochotkaew1@ibm.com>
> draft for kepler CR

- .github/workflows/integration_test.yml
- Makefile
- cluster-up/cluster-down.sh
- cluster-up/cluster-up.sh
- cluster-up/cluster/kind/README.md
- cluster-up/cluster/kind/common.sh
- cluster-up/cluster/kind/manifests/kind.yml
- cluster-up/cluster/kind/manifests/local-registry.yml
- hack/cluster-down.sh
- hack/cluster-up.sh
- scripts/clusterup.sh
> GH Actions for integration tests

- .github/workflows/integration_test.yml
> GH Actions build & push operator container image to registry

- .github/workflows/integration_test.yml
> [TEST PR] Test GH Actions

- .github/workflows/integration_test.yml
> FIX GH Actions

- .github/workflows/gofmt.yml
- .github/workflows/gogc.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/govulnerability.yml
- .github/workflows/integration_test.yml
- .gitignore
- Makefile
- automation/presubmit-tests/gofmt.sh
- Add no function checks for golang.
- Switch to org internal GHA for kind cluster set up.
Signed-off-by: Sam Yuan <yy19902439@126.com>
> CI: enhancement

- api/v1alpha1/kepler_types.go
Included Descriptors in Kepler Types.
> Include Descriptors

- .github/workflows/release.yaml
This PR adds the GH Workflow to create release and tag and push the tagged image to quay.
> Add release GH Workflow

- controllers/kepler_controller.go
Following https://github.com/sustainable-computing-io/kepler/pull/604/files
> change a config for listing pods to use ip #604

- .github/workflows/integration_test.yml
a part as pre-request of https://github.com/sustainable-computing-io/kepler-action/pull/46
> use Version Control For our kepler Action

- config/manager/kustomization.yaml
- config/samples/kepler.system_v1alpha1_kepler.yaml
- controllers/kepler_controller.go
- controllers/sahandler.go
Merge following kepler ds changes into the operator
- https://github.com/sustainable-computing-io/kepler/pull/578
- https://github.com/sustainable-computing-io/kepler/pull/683
- https://github.com/sustainable-computing-io/kepler/pull/635
- https://github.com/sustainable-computing-io/kepler/pull/733
Related Issues:
- https://github.com/sustainable-computing-io/kepler-operator/issues/76
- https://github.com/sustainable-computing-io/kepler-operator/issues/75
> kepler-operator to follow kepler 0.5

- CONTRIBUTING.md
- Operator-SDK.md
- README.md
https://github.com/sustainable-computing-io/kepler-operator/issues/80
> Doc: Fixing some typos

- Makefile
- config/manager/kustomization.yaml
This PR fixes `make deploy` when used to deploy the operator on local env.
> Fix make deploy

- controllers/kepler_controller.go
Fixes https://github.com/sustainable-computing-io/kepler-operator/issues/95
> Change log verbosity to 1

- .github/workflows/gofmt.yml
- .github/workflows/gogc.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/govulnerability.yml
- .github/workflows/image.yaml
- .github/workflows/integration_test.yml
- Fixes #101 
Signed-off-by: Parul Singh <parsingh@redhat.com>
> Add go version from go.mod in GH Workflow

- Makefile
This PR fixes the repo name inside Makefile
> fix repo name

- Makefile
- bundle/ci.yaml
- bundle/manifests/kepler-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/manifests/bases/kepler-operator.clusterserviceversion.yaml
- hack/bundle.sh
This PR:
1. adds support to make yq part of make tools.
2. change the directory from config/manager to config/manifests while setting the image controller.
3. move the bundle.Dockerfile to bundles dir post generating bundle.
> fix make bundle

- Makefile
- hack/tools.sh
- hack/utils.bash
This PR fixes issue [133](https://github.com/sustainable-computing-io/kepler-operator/issues/133)
> Add tools.sh

- bundle/manifests/kepler-operator.clusterserviceversion.yaml
- bundle/manifests/kepler.system.sustainable.computing.io_keplers.yaml
- cmd/manager/main.go
- config/crd/bases/kepler.system.sustainable.computing.io_keplers.yaml
- config/samples/kepler.system_v1alpha1_kepler.yaml
- pkg/api/v1alpha1/kepler_types.go
- pkg/components/exporter/exporter.go
Fixes: https://github.com/sustainable-computing-io/kepler-operator/issues/137
> feat!: pin kepler version to 0.5.4

- hack/uninstall-operator.sh
This PR allows --version 0.5.0 or --verison v0.5.0 to be passed.
> fix(uninstall): handle operator version gracefully

- hack/dashboard/assets/dashboard.json
-  Removed "Carbon Emissions" panel from dasboard.
-  Removed variables for Coal, Petroleum, Natural Gas.
Dashboard after change:
> fix: removed "Carbon Emissions" panel from dasboard.

- Makefile
Default make target (all) now brings up a cluster, builds operator and
bundle images, provides instructions on how to run the operator.
> Improve default target

- Makefile
- docs/api.md
- hack/tools.sh
Code added to generate api.md file
> feat: generate api docs

- hack/dashboard/openshift/deploy-grafana.sh
This PR updates the availability checks for Kepler and user-workload-monitoring in deploy-grafana.sh
> add availability checks for uwm & kepler

- docs/developer/test-plan.md
Update install plan for
*  installing from dev-preview channel
* ensuring that reconcile loop is not infinite
> docs: update test plan for dev-preview release

- hack/cluster.sh
- pkg/utils/test/framework.go
- pkg/utils/test/oc/adm_top.go
- pkg/utils/test/oc/command.go
- pkg/utils/test/oc/doc.go
- pkg/utils/test/oc/exec.go
- pkg/utils/test/oc/exec_test.go
- pkg/utils/test/oc/get.go
- pkg/utils/test/oc/get_test.go
- pkg/utils/test/oc/literal.go
- pkg/utils/test/oc/literal_test.go
- pkg/utils/test/oc/logs.go
- pkg/utils/test/oc/runner.go
- tests/e2e/kepler_test.go
- tests/e2e/oc/get_test.go
- tests/e2e/oc/literal_test.go
This PR adds e2e tests for testing node selector and Tolerations.
> feat(test): added e2e tests for node selector and Tolerations

- bundle/manifests/kepler-operator.clusterserviceversion.yaml
- config/manifests/bases/kepler-operator.clusterserviceversion.yaml
> feat(bundle): add description about enabling UWM

- pkg/utils/test/framework.go
- tests/e2e/kepler_test.go
This PR moves the  helper functions from `kepler_test.go` to `framework.go`
> test(refactor): move helper functions

- docs/developer/test-plan.md
This PR updates the test plan to reflect the changes that went in `dev-preview` release.
> docs(test-plan): Update test-plan

- pkg/utils/test/framework.go
- tests/e2e/kepler_test.go
This PR adds negative tests for node selectors and tolerations.
> test: Add negative test for node selector and tolerations

- tests/run-e2e.sh
Previously, in CI, the operator bundle was installed on a clean cluster instead of the scenario where the bundle is upgraded. This has resulted in bundle getting rejected in Community Operator Catalog when the upgrade test failed.
This commit modifies the e2e test to run the upgrade scenario instead of installing on a fresh cluster.
> ci: test bundle-upgrade scenario

- Makefile
- hack/tools.sh
This PR adds `jq` installation to make tools.
> feat: add jq installation to tools

- bundle/manifests/kepler-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
This PR adds `--deployment-namespace` argument to controller deployment
> fix(csv): Add deployment-namespace argument to controller deployment

- tests/run-e2e.sh
This PR remove container images before running e2e tests to reclaim more space.
> ci: reclaim space before running tests

- hack/cluster.sh
This adds the deployment for cert-manager to the cluster.sh script Now running `make cluster-up` will also make sure that cert-manager is deployed on Kind cluster
> feat: Add cert-manager deployment to cluster.sh

- bundle/ci.yaml
- bundle/manifests/kepler-operator.clusterserviceversion.yaml
- config/manifests/bases/kepler-operator.clusterserviceversion.yaml
- hack/bundle.sh
This commit updates the maintainers by adding @vprashar2929 to the list.
> chore: add vprashar to the maintainers list

- LICENSE-APACHE
> chore(license): Add APACHE license file

- README.md
This commit updates the README with the latest information about the Operator.
Key changes:
- Add steps to deploy the Operator on OpenShift
- Improve the formatting and linting
> doc: update the README

- .github/codecov-upload/action.yaml
- .github/workflows/pr-checks.yaml
- .github/workflows/publish-images.yaml
This commit adds support for uploading the test results to codecov.
> ci: add support for codecov

- README.md
This commit updates the README to include the relevant status of the project like:
- CI status
- Codecov status
- Release status
> docs: add relevant status in the README

- pkg/components/power-monitor/deployment.go
This commit renames the kepler config file from `kepler-config.yaml` to `config.yml`
> chore: rename kepler config file

- Makefile
- bundle/manifests/kepler-operator.clusterserviceversion.yaml
- internal/config/builder.go
- internal/config/config.go
- internal/config/config_test.go
- internal/controller/config.go
- pkg/components/power-monitor/deployment.go
- pkg/components/power-monitor/deployment_test.go
- tests/e2e/main_test.go
This commit bumps up kepler reboot version to 0.7.0 along with config changes.
> chore: bump up kepler reboot

- Makefile
- bundle/manifests/kepler-operator.clusterserviceversion.yaml
- internal/config/config.go
- internal/config/config_test.go
- internal/controller/config.go
- pkg/components/power-monitor/deployment.go
- pkg/components/power-monitor/deployment_test.go
- tests/e2e/main_test.go
This PR requires changes from https://github.com/sustainable-computing-io/kepler/pull/2127 
Updated config 
Updated deployment spec
Updated tests
> feat(pod): Operator support Pod power

- api/v1alpha1/kepler_internal_types.go
- api/v1alpha1/kepler_types.go
- bundle/manifests/kepler-operator.clusterserviceversion.yaml
- bundle/manifests/kepler.system.sustainable.computing.io_keplerinternals.yaml
- bundle/manifests/kepler.system.sustainable.computing.io_keplers.yaml
- config/crd/bases/kepler.system.sustainable.computing.io_keplerinternals.yaml
- config/crd/bases/kepler.system.sustainable.computing.io_keplers.yaml
- config/manifests/bases/kepler-operator.clusterserviceversion.yaml
- docs/api.md
This commit updates the Kepler/KeplerInternal CR description to include a deprecation notice.
> chore: add deprecation notice to Kepler CR description

- tests/run-e2e.sh
This commit updates the bundle upgrade test to check PowerMonitor CR status and validate the Kepler image after the upgrade.
> test: validate PowerMonitor CR and Kepler image in upgrade test

- hack/dashboard/assets/kepler/dashboard.json
- hack/dashboard/openshift/deploy-grafana.sh
This commit updates the deploy grafana script according to new PowerMonitor CR
It also updates the dashboard to match with what we have in the OpenShift dashboard
> chore: update deploy grafana script

- pkg/components/power-monitor/deployment_test.go
This commit improves the code coverage for the power-monitor component.
> test: improve code coverage for power-monitor

- pkg/reconciler/finalizer_test.go
- pkg/reconciler/power-monitor_test.go
- pkg/reconciler/runner.go
- pkg/reconciler/runner_test.go
- pkg/reconciler/security_test.go
- pkg/reconciler/service_monitor_test.go
This commit introduces tests for all available reconcilers significantly improving the overall test coverage.
> test: add comprehensive tests for reconcilers

- README.md
- manifests/helm/kepler-operator/Chart.yaml
- must-gather/README.md
This commit updates the v1alpha1 reference to main
> docs: update v1alpha1 reference to main
