.github/workflows/image.yaml, .github/workflows/integration_test.yml
This PR moves creates two workflows. 
- intergration.yaml : to build and e2e test the operator on kind
- image.yaml will make and push image to quay on `push` instead of `pull_request` 
=>  test push-image gha

controllers/kepler_controller.go, controllers/kepler_controller_unit_test.go, controllers/kepler_naming_conventions.go, controllers/machineconfig_controller.go, controllers/model_server_handler.go, controllers/sahandler.go, controllers/scc_controller.go
This update includes defining a list of constants for defining kepler objects name and namespaces. The defined constants are the suffixes since kubernetes objects can include kepler object's name and namespace as the prefix.
=> Update Naming Convention for Kubernetes Objects

.devcontainer/devcontainer.json, .devcontainer/scripts/install-tools.sh, .gitignore, README.md
Made the following additions that creates a reproducible go development environment using Docker, Visual Studio Code, and the Dev Containers extension:
- Added a `.devcontainer` folder to configure the VSCode Dev Container extension to provide:
- go
- docker-in-docker
- oc
- kubectl
- helm
- kustomize
- kind
- Updated the `README.md` to add a paragraph about this new capability 
To activate, open the project with:
```bash
cd kepler-operator
code .
```
Then press the **Reopen in Container** button and a development environment will be created.
=> Added support for VSCode Dev Containers

controllers/kepler_controller.go, controllers/kepler_controller_unit_test.go
With Single Node Openshift (and presuambly others) port 9102 is already used by the OVN Kubernetes CNI. Attempting to reuse it caused the kepler-exporter pod to get stuck in 'pending' because it couldn't get the hostport it wanted.  This commit removes the requirement for host networking and HostPort: 9102 from kepler-export, which allows it to run on.
This is the same issue as https://github.com/sustainable-computing-io/kepler/issues/527 and the same fix ported over.
=> remove HostPort that causes conflicts with SNO's CNI over port 9102

README.md, config/samples/kustomization.yaml
When running `kubectl apply -k config/samples/` kubectl throws the following error: 
```
kubectl apply -f config/samples/
kepler.kepler.system.sustainable.computing.io/kepler created
error: resource mapping not found for name: "" namespace: "" from "config/samples/kustomization.yaml": no matches for kind "Kustomization" in version "kustomize.config.k8s.io/v1beta1"
ensure CRDs are installed first
```
Instead of using `kubectl apply -f` we can also use `kubectl apply -k` to avoid running `kustomize build` every time when applying the sample.
=> Fix error when deploying kepler-operator locally

.gitignore, Makefile, README.md
This PR improves on how operator is run locally by
1. installing local-dev-cluster to a tmp directory
2. moving all tools (controller-gen, kustomize etc) to tmp/bin
3. Adding a section explaining running operator out of cluster
=> Improve running operator locally

Makefile, hack/cluster.sh
This PR bump-ups the version of local-dev-cluster to 0.0.3
=> bump up local-dev-cluster version to 0.0.3

hack/cluster.sh
This PR updates the `cluster.sh` to use `operator-sdk` binary which is installed as part of `make tools`. This allows the script to use the specific version of `operator-sdk` hence not interfering with the version installed on the user's machine
=> Update cluster.sh to use operator-sdk from make tools

.github/workflows/image.yaml
This PR fixes the path for running run-e2e.sh in gh workflow. Reference to a [failed](https://github.com/sustainable-computing-io/kepler-operator/actions/runs/5815701708/job/15767681380#step:5:10) CI run
=> fix gh workflow to use correct path

.github/workflows/image.yaml
This PR fixes image workflow post these [changes](https://github.com/sustainable-computing-io/kepler-operator/pull/139) done to `run-e2e.sh`. Since we no longer build and push images from the script. The current [CI](https://github.com/sustainable-computing-io/kepler-operator/actions/runs/5855976948/job/15874787916) run fails.
=> fix broken image workflow

.github/compute-version/action.yaml, .github/publish-images/action.yaml, .github/workflows/image.yaml, .github/workflows/integration_test.yml
This patch validates that the images can be built and that the bundle
is validated by
* refactoring version computation
* refactoring image builds to a separate action that is reused
=> ci: validate images can be built with right version pre-merge

pkg/components/exporter/exporter.go, pkg/utils/k8s/k8s.go
This PR 
- updates `kepler-exporter-cm` to sync with latest config of kepler. as per [kepler repo manifest](https://github.com/sustainable-computing-io/kepler/blob/main/manifests/config/exporter/exporter.yaml#L11-L34)
- fixes kepler command line args in kepler daemon set to use values from  `kepler-exporter-cm` 
fixes: #111
=> Update kepler cm

.github/workflows/integration_test.yml
This PR removes the redundant e2e-success step from [integration-test](https://github.com/sustainable-computing-io/kepler-operator/blob/31e6dff51eee3c6a1093b470747c0d1c561a5597/.github/workflows/integration_test.yml#L46) workflow
=> remove e2e-success step from workflow

.github/workflows/integration_test.yml, bundle/manifests/kepler-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, bundle/manifests/kepler-operator-controller-manager-metrics-service_v1_service.yaml, bundle/manifests/kepler-operator.clusterserviceversion.yaml, config/default/kustomization.yaml, config/manager/manager.yaml, config/prometheus/monitor.yaml, config/rbac/auth_proxy_service.yaml, tests/run-e2e.sh
This patch removes the kube-rbac-proxy so that metrics of the operator
can be scrapped without any auth(z). It additionally adds a service
monitor to the bundle so that the operator can be monitored if User
Project Monitoring is enabled in the OpenShift cluster.
Fixes: https://github.com/sustainable-computing-io/kepler-operator/issues/145
=> feat: enable monitoring of kepler-operator

hack/dashboard/assets/dashboard.json
This PR attempts to improve kepler grafana dashboard by
- moving the `topk(10) Power Namespace` to the top
- change the panel to sort top 10 namespace by power consumption
- make `openshift-kepler-operator` namespace default value for the `namespace` dashboard variable
This PR includes new panel as well as old panel for review purpose. Once review is done, old panel can be removed.
[Screenshot] Old and New panel :
[Screenshot] Default selected namespace: `openshift-kepler-operator`
=> feat: dashboard: improve topk(10) power consumption namespace panel

docs/developer/test-plan.md
This PR moves test-plan from #172 to `docs/developer`
=> doc: Add operator test-plan to docs

hack/dashboard/assets/dashboard.json
This PR removes the old `topk(10)` namespaces panel which was left for review in earlier PR #208 
new dashboard starts with
=> fix: removed old topk(10) namespace panel

pkg/controllers/kepler.go
Since deleting a namespace deletes all objects inside it, the reconciler only needs to delete the components namespace and wait for the deletion to complete.
=> feat: faster deletion reconciliation loop

bundle/manifests/kepler-operator.clusterserviceversion.yaml, config/manifests/bases/kepler-operator.clusterserviceversion.yaml
This commit fixes the installation of bundle on openshift which fails because of the required CRD servicemonitor (which is provided by Prometheus Operator). Although the CRD is present in the cluster, OLM seems to be installing PO which conflicts with the in-cluster Prometheus Operator. The fix is to remove the dependency in CSV on ServiceMonitors
=> fix(bundle): installation of bundle on openshift

Makefile, bundle/manifests/kepler-operator.clusterserviceversion.yaml, cmd/manager/main.go, config/manager/manager.yaml, pkg/controllers/kepler.go, pkg/utils/k8s/k8s.go
This PR add a `--openshift` flag to operator which instructs operator
to deploy components that are specific to openshift only if the flag is
set. This allows the operator to be run against a vanilla k8s cluster by
not setting this flag (which is the default).
=> feat: support vanilla k8s cluster

Makefile, bundle/manifests/kepler-operator.clusterserviceversion.yaml, bundle/manifests/kepler.system.sustainable.computing.io_keplers.yaml, config/crd/bases/kepler.system.sustainable.computing.io_keplers.yaml, pkg/api/v1alpha1/kepler_types.go
`kubectl get kepler` did not print the exporter port and the nodeSelectors after
the refactor for deployment settings to `deployment` field. This fixes the `printcolumns`
to point to the right path.
=> fix: print-columns after exporter spec refactor

Makefile, bundle.Dockerfile, bundle/manifests/kepler-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml
When a bundle has more than on channel annotation, it must also have the annotation for indicating the default channel, otherwise the bundle gets rejected by the community-catalog CI.
This was required for making the 0.8.0 release
See: https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3253
=> fix(bundle): setting default channel to alpha

hack/tools.sh
This PR adds support for deploying oc with version 4.13.0 as part of `make tools`
=> feat: add oc to make tools

.github/workflows/pr-checks.yaml, Makefile, hack/bundle.sh, hack/tools.sh
* removes unnecessary rebases due to bundle generation
* Adds make target for installing oc
* Removes (ab)use of [[ $(command -v ...) ]] with command -v
=> improve dev UX by removing unnecessary toil

.github/workflows/release.yaml
This PR updates the release workflow to include `VERSION_REPLACED` while building the bundle. This will be useful when publishing the bundle to the community catalog.
Test workflow [run](https://github.com/vprashar2929/kepler-operator/actions/runs/6175536737/job/16762617447#step:7:54)
=> chore: update release workflow to include version replaces in bundle

hack/dashboard/openshift/deploy-grafana.sh
This PR adds the info inside `deploy-grafana.sh` related to how to do custom configuring of Prometheus deployed by uwm according to requirement.
=> style: Add info related to uwm in Grafana script

Makefile, bundle/manifests/kepler-operator.clusterserviceversion.yaml, cmd/manager/main.go, config/manager/manager.yaml, hack/bundle.sh, pkg/components/exporter/exporter.go, tests/run-e2e.sh
For dev testing sometimes it is needed to change the kepler image to be deployed. This PR lets devs use an env variable to specify the kepler image.
- Makefile: variable(s) for defining kepler image, which form the 'official' image used in the bundle, but whose value can be overridden by user while building bundle
- CSV: added env variable `RELATED_IMAGE_KEPLER` in kepler operator deployment which gets passed as an argument to manager, and its value can be overridden by user while building the bundle by supplying env variables `KEPLER_IMG` or `KEPLER_VERSION`
- exporter/main/go: changed to use the new env variable `RELATED_IMAGE_KEPLER`
- hack/bundle.sh: replace `KEPLER_IMG` with its value in CSV
- operator-sdk adds `relatedImages` field based on `RELATED_IMAGE*` variables used
**Example …
=> feat(bundle): Use user supplied kepler image

hack/cluster.sh, pkg/components/exporter/assets/kepler-dashboard.json, pkg/components/exporter/exporter.go, pkg/controllers/kepler.go
The PR 
*  add kepler dashboard resource which is configmap applied to openshift-config-managed namespace
* creates kepler dashboard if running against openshift
* ensures namespace for creating dashboard exists in CI cluster
=> feat(dashboard): create dashboards for Kepler on OpenShift

.github/publish-images/action.yaml, Makefile, tests/Dockerfile
This PR creates a Dockerfile under the `tests` dir which will build a test binary that downstream prow CI will consume in running e2e tests on OpenShift.
=> feat: package go test to run in prow CI

README.md, hack/uninstall-operator.sh
This commit improves the experience of using the uninstall script by
automatically finding the version of kepler-operator installed. So, user
need not explicitly specify the version to installed (but they can
should they choose to) to uninstall.
It also adds a --help option to the script to print the usage
=> feat: improve uninstall script to find the installed version

pkg/utils/test/framework.go, tests/e2e/kepler_test.go
This PR adds the check for any error in the case when cleanup happens.
=> test: Add error check during cleanup

pkg/components/exporter/assets/dashboards/power-monitoring-by-ns.json, pkg/components/exporter/assets/dashboards/power-monitoring-overview.json
This commits brings in the fixes added to kepler repo by PR: https://github.com/sustainable-computing-io/kepler/pull/948
Following changes are also made
* remove repeated namespace from all legends
* make Overview as the first item in the dropdown list by adding a space before ` O`verview
=> fix: promql used in openshift dashboards

bundle/manifests/kepler-operator.clusterserviceversion.yaml, config/rbac/role.yaml, pkg/components/exporter/assets/dashboards/power-monitoring-by-ns.json, pkg/components/exporter/assets/dashboards/power-monitoring-overview.json, pkg/components/exporter/exporter.go, pkg/controllers/kepler.go
This commit improves the rendering of dashboards by taking advantage of Prometheus recording rules to pre-compute queries which may otherwise take too much memory (resulting in Prometheus OOM crash) or time for the query to execute.
The Operator deploy a `PrometheusRule` resource which pre-computes queries used in openshift dashboards.
=> feat(dashboard): use prometheus recording rules faster queries

pkg/components/exporter/assets/dashboards/power-monitoring-by-ns.json
This PR:
* Move the `Total Power Consumption (W) in Namespace` and `Total Energy Consumption in Namespace (kWh) - Last 1 hour` panels to the beginning.
Screenshots:
=> fix(dashboard): update layout for namespace dashboard

hack/dashboard/assets/kepler/dashboard.json
This PR:
* Updates the visualization type and respective configuration of existing panels in the dashboard to show the information in a meaningful way.
* Break Pod/Process Power consumption panel into isolated panels on the basis of the type of process.
* Move the Total Power Consumption graph panel below the Top10 namespace panel.
* Add a description for each panel along with a tooltip that links to [Kepler-docs](https://github.com/sustainable-computing-io/kepler-doc/blob/84e3e01a0110829937cd40f9634dd8d0c92540a4/docs/design/metrics.md#monitoring-container-power-consumption-with-kepler)
=> fix(dashboard): fix current Grafana dashboard

Dockerfile, must-gather/README.md, must-gather/common, must-gather/gather, must-gather/gather-kepler-exporter-info, must-gather/gather-kepler-operator-info, must-gather/gather-olm-info
Thie PR adds `must-gather` scripts for kepler-operator
Sample execution on single node CRC cluster:
```
$ oc adm must-gather --image=$(oc -n openshift-operators get deployment.apps/kepler-operator-controller-manager -o jsonpath='{.spec.template.spec.containers[?(@.name == "manager")].image}')  -- /usr/bin/gather 
[must-gather      ] OUT Using must-gather plug-in image: quay.io/vimalkum/kepler-operator:0.0.0-must-gather
When opening a support case, bugzilla, or issue please include the following summary data along with any other requested information:
ClusterID: 1f7b621c-7e7a-4ca8-81d5-f49ad9d9acb6
ClusterVersion: Stable at "4.13.12"
ClusterOperators:
clusteroperator/cloud-credential is missing
clusteroperator/cluster-autoscaler is missing
clusteroperator/insights is missing …
```
=> feat(must-gather): Added must-gather scripts

hack/dashboard/assets/kepler/dashboard.json
This PR adds the remaining panels to the Grafana dashboard. This inclines with what we have in OpenShift dashboard
Screenshot:
=> feat(dashboard): add remaining panels to grafana dashboard

hack/cluster.sh, hack/monitoring/rbac/prometheus-cr.yaml, hack/monitoring/rbac/prometheus-k8s-full-crb.yaml
Previously, prometheus deployed to monitoring namespace wasn't able to discover kepler deployed to `openshift-kepler-operator` because it lacked the rbac to discover services outside `monitoring` namespace. This commit fixes it by adding additional rbac rules allowing all services to be discovered.
=> fix(kind): ensure prometheus can discover all services

cmd/manager/main.go
This commit fixes following reconcilation error when deleting dashboards installed to `openshift-config-managed` namespace.
```
continue reconciliation despite error   {"name":"kepler", "error": "power-monitoring-overview (/v1, Kind=ConfigMap): deleter: timed out waiting for deletion : timed out waiting for the condition"}
continue reconciliation despite error   {"name":"kepler", "error": "power-monitoring-by-ns (/v1, Kind=ConfigMap): deleter: timed out waiting for deletion : timed out waiting for the condition"}
finalizer state                         {"name":"kepler", "reconciler": "finalizer", "deleted": true, "finalizer": true}
2023-10-06T08:24:03Z    ERROR   Reconciler error        {"controller": "kepler", "controllerGroup": "kepler.system.sustainable.computing.io", "controllerKind": …
```
=> fix: deletion error when deleting dashboard configmaps

bundle/manifests/kepler.system.sustainable.computing.io_keplers.yaml, config/crd/bases/kepler.system.sustainable.computing.io_keplers.yaml, docs/api.md, pkg/api/v1alpha1/kepler_types.go, pkg/components/exporter/exporter.go, pkg/components/exporter/exporter_test.go, tests/e2e/kepler_test.go
Previously, `kubectl get kepler -o wide` did not show the default toleration applied viz. {"operator": "Exists"}
This PR fixes it by moving the default toleration to the CRD spec itself
Fixes: https://github.com/sustainable-computing-io/kepler-operator/issues/186
=> fix(api): define default toleration in Kepler CRD

Makefile, bundle/manifests/kepler-operator.clusterserviceversion.yaml, pkg/components/exporter/exporter.go
Note for future maintainers
We skipped 0.6.0 release of kepler due to https://github.com/sustainable-computing-io/kepler/issues/973
=> feat(kepler): upgrade to kepler 0.6 release

pkg/components/exporter/exporter.go
The 'idle' value refers to the total host idle power, which is not distributed among all the running VMs on the node. Consequently, each VM may wrongly double-count the host's idle time if there are multiple VMs on the same host.
In public cloud environments, it is impractical to determine the number of running VMs on a node. This parameter is intended for use only one bare metal servers that rely on node power estimation because they do not provide real-time power metrics, or when there is only one VM running on the host for very specific scenarios.
So, lets enable this setting through Kepler spec (new feature).
Ref: https://github.com/sustainable-computing-io/kepler/issues/973#issuecomment-1760680200
=> fix(exporter): do no enable estimated idle power by default

pkg/utils/test/oc/runner.go
Previously, when KUBECONFIG is not set, instead of oc defaulting to ~/.kube/config, it uses KUBECONFIG that points no where and tests fail as follows:
```
❯ go test -v ./tests/e2e/... -run Node -count=1 -timeout=15m
=== RUN   TestNodeSelector
Running command cmd oc args [get node -o jsonpath={.items[*].metadata.name}]
kepler_test.go:90:
Error:          Received unexpected error: exit status 1
Messages:       failed to get node names
kepler_test.go:91:
Error:          Should not be zero, but was 0
Messages:       got zero nodes
--- FAIL: TestNodeSelector (0.08s)
panic: runtime error: index out of range [0] with length 0 [recovered]
panic: runtime error: index out of range [0] with length 0
```
This commit fixes the issue by exporting KUBECONFIG only if it is not empty.
=> fix(test): export KUBECONFIG to oc only if set

.github/publish-images/action.yaml, .github/tools-cache/action.yaml, .github/workflows/pr-checks.yaml, .github/workflows/release.yaml
This PR fixes issue https://github.com/sustainable-computing-io/kepler-operator/issues/203
CI runs:
Cache: https://github.com/vprashar2929/kepler-operator/actions/caches
Install tools: https://github.com/vprashar2929/kepler-operator/actions/runs/6561587421/job/17822440775#step:4:18
Sample run: https://github.com/vprashar2929/kepler-operator/actions/runs/6561587421
=> feat(ci): add support to cache tools in CI

bundle/manifests/kepler-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, bundle/manifests/kepler-operator-controller-manager-metrics-service_v1_service.yaml, bundle/manifests/kepler-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/kepler-operator.clusterserviceversion.yaml, config/prometheus/monitor.yaml, config/rbac/auth_proxy_service.yaml, must-gather/gather, must-gather/gather-kepler-operator-info
Previously, deploying operator created deployment that used generic
`control-plane: controller-manager` label. This causes external tools
(including the must-gather script) to lookup pods that can belong to
**any** deployment that has this label. This commit replaces the label
with `app.kubernetes.io/instance: controller-manager`.
Fixes: https://issues.redhat.com/browse/POWERMON-159
=> fix(deployment): do not use generic k8s labels

go.mod, pkg/utils/test/framework.go, tests/e2e/kepler_test.go
This PR updates the test for taints and tolerations to use only nodes that don't have any taints applied.
=> test(ci): update taints and tolerations test

Makefile, bundle/manifests/kepler-operator.clusterserviceversion.yaml, cmd/manager/main.go, config/manager/manager.yaml, hack/bundle.sh, pkg/components/exporter/exporter.go, pkg/components/exporter/exporter_test.go
This PR reads value of annotation `"app.kubernetes.io/kepler-bpf-attach-method"` on Kepler object to decide which bpf type image to be deployed.
If the value is `"libbpf"` , the image `quay.io/sustainable_computing_io/kepler:release-0.6.1-libbpf` is chosen, else `quay.io/sustainable_computing_io/kepler:release-0.6.1` is used. 
This is a temporary fix to let users choose libbpf image till kepler upstream makes libbpf as the default attach method.
fixes: https://issues.redhat.com/browse/POWERMON-166
=> feat: Use Kepler annotation to choose bcc or libbpf kepler image

Makefile, config/samples/kepler.system_v1alpha1_kepler.yaml, pkg/components/exporter/exporter.go, pkg/components/exporter/exporter_test.go
This PR includes 3 minor corrections / modifications 
1. Fix `make run-k8s` which had an additional `-` in the arg by replacing both `run` and `run-k8s` with just a single `run` target `make run OPENSHIFT=[true]|false`
3. Use kepler.sustainable.computing.io namespace for kepler related annotations 
4. Add a comment in kepler sample explaining how to enable libbpf
=> Minor corrections and Doc changes to bpf deployment

Dockerfile
Images in [quay repo](https://quay.io/repository/sustainable_computing_io/kepler-operator?tab=tags) show lot of vulnerabilities.
Updated base image to fix vulnerabilities.
=> chore(Dockerfile): Update base image to fix vulnerabilities

Makefile
This PR fixes the issue when running `make fresh` command. `IMG_BASE` points to `localhost:5001`. This var is also used in `KEPLER_IMG` and `KEPLER_IMG_LIBBPF`. At the time of creating the instance cluster tries to pull the Kepler image from local registry which we don't build and push to.
=> chore: update make fresh

must-gather/gather, must-gather/gather-monitoring-info
This PR adds support for capturing `User-Workload-Monitoring` related info in must-gather
=> feat: enable must-gather for uwm

hack/tools.sh
This PR updates `tools.sh` to make use of existing `validate_version` function.
=> chore: update tools.sh

bundle/manifests/kepler.system.sustainable.computing.io_keplerinternals.yaml, cmd/manager/main.go, config/crd/bases/kepler.system.sustainable.computing.io_keplerinternals.yaml, pkg/api/v1alpha1/kepler_internal_types.go
This PR made a small fix on status and add TODO when different namespace is introduced later by the KeplerInternal CR (not include in the command flag). 
Signed-off-by: Sunyanan Choochotkaew <sunyanan.choochotkaew1@ibm.com>
=> fix missing UP-TO-DATE status field

hack/dashboard/assets/kepler/dashboard.json, tests/run-e2e.sh
This PR removes the occurrence of `openshift-kepler-operator`
**Note:** Didn't removed it from must-gather scripts.
=> fix: remove any occurrence of openshift-kepler-operator

pkg/components/estimator/estimator.go, pkg/utils/test/assertions.go, pkg/utils/test/framework.go, tests/images.yaml, tests/run-e2e.sh
Currently, CI fails because model-server image absent in CI and  validation does not wait enough for Model Server to be running. This is fixed by 
1. allowing additional  images to be loaded into cluster and using that to load model-server image
2. improving  the validation of model-server and estimator into 2 functions which provide each amble time to be up and running.
=> ci: improve model-server and estimator validation

bundle/manifests/kepler-operator.clusterserviceversion.yaml, config/manifests/bases/kepler-operator.clusterserviceversion.yaml
NOTE: this annotation is now a requirement for publishing operators to community catalog and had to be manually added to release 0.10.0 See: https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3862
=> fix(CSV): add required support annotation

pkg/controllers/kepler_internal.go
This commit fixes kepler-internal controller to prevent infinite reconciliation caused by status updates even when there aren't any.
=> fix(controller): update status only if needed

pkg/components/exporter/assets/dashboards/power-monitoring-overview.json
This commit adds the `components_power_source` and `platform_power_source` info to the cluster overview dashboard in OpenShift.
=> feat(dashboard): show node power source info

pkg/components/exporter/assets/dashboards/power-monitoring-overview.json
This commit adds a detailed node power information table to the overview dashboard. It also works around the OpenShift dashboard UI bug when rendering tables. The bug is that the first column must have unique values. This caused only a single CPU information to be rendered as `kepler_node_info` had components_power_source to be the first item in the list which had `estimator` as the only value.
A similar workaround is applied for "Detailed Node Information" table to have `instance` as the first field in the prometheus query result.
The issue is better explained in https://issues.redhat.com/browse/OU-309
=> feat(dashboard): add detailed node power information

tests/e2e/main_test.go
This is required to support running tests when kepler is deployed to
non-default namespace. E.g. on OpenShift, it may be deployed onto a
different namespace than the default `kepler-operator`.
=> fix(test): accept deployment ns

hack/dashboard/assets/kepler/dashboard.json
This PR updates the Grafana dashboard to be inclined with the OpenShift console
=> chore: update Grafana dashboard

Makefile
This PR updates `make deploy` to change `<KEPLER_IMG>` to the actual `KEPLER_IMG` value
=> fix: update make deploy target to use KEPLER_IMG

must-gather/common
Use labels to get correct namespace name.
=> POWERMON-199: Use correct kepler namespace in must-gather

must-gather/gather, must-gather/gather-olm-info, must-gather/gather-power-monitoring-operator-info
fix gather power-monitoring-operator info
=> POWERMON-199: fix gather power-monitoring-operator info

hack/uninstall-operator.sh
This PR fetches the operator name`(power-monitoring-operator/kepler-operator)` from the cluster instead of the hard code name.
=> feat: update uninstall script to capture operator name

tests/run-e2e.sh
This PR updates the run-e2e script steps where we are calling operator-sdk via `./tmp/bin/operator-sdk` Currently the script breaks if `make tools` skips installing `operator-sdk` due to the availability of the expected version of `operator-sdk` locally.
=> fix: Update run-e2e script

pkg/utils/test/assertions.go, pkg/utils/test/framework.go, tests/e2e/kepler_internal_test.go
This PR increases the timeout when checking the status for KeplerInternal. It is in relation to frequent failures that are seen on Prow CI when e2e tests are triggered.
Ref:
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-power-monitoring-power-monitoring-operator-v1alpha1-ocp4.14-periodic-power-monitoring-operator-e2e-gcp/1762719530259320832
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-power-monitoring-power-monitoring-operator-v1alpha1-ocp4.14-periodic-power-monitoring-operator-e2e-aws/1762719528157974528
=> fix: update ki e2e to have higher timeout 

pkg/controllers/kepler.go, pkg/controllers/kepler_internal.go
Previously error (recErr) while running reconcilers were ignored by both kepler and kepler-internal controllers which resulted in reporting in conditions.Reconciled as success even though it failed. The commit fixes that oversight.
=> fix: report failure during reconciliation correctly

pkg/components/exporter/exporter.go
This PR adds the label `console.openshift.io/odc-dashboard` to the dashboards config map which allows dashboards to be visible in the developer console. 
For user to see the values the user must have view permissions for the project that the dashboard is for i.e `kepler-operator`
=> feat: allow dashboard to show in OpenShift developer console

bundle/manifests/kepler-operator.clusterserviceversion.yaml, config/rbac/role.yaml, pkg/components/exporter/exporter.go, pkg/components/exporter/exporter_test.go, pkg/controllers/kepler_internal.go, pkg/reconciler/kepler.go, pkg/reconciler/reconciler.go, pkg/utils/k8s/k8s.go, tests/e2e/kepler_internal_test.go
This PR 
* removes the RBAC role provided to both operator and kepler. 
* Condition now contains the namespace where redfish secret is expected to be present.
* reorgs the code to follow naming convention
* Uses `ContainerIndex` type to refer to a container in `spec.containers`
* Make Redfish test that failed with the follow error message more robust by waiting for controller to reconcile
```
--- FAIL: TestKeplerInternal_ReconciliationWithRedfish (0.09s)
panic: runtime error: index out of range [0] with length 0 [recovered]
panic: runtime error: index out of range [0] with length 0
```
=> feat(redfish): reduce rbac permission given to operator and kepler for handling secrets

pkg/api/v1alpha1/kepler_types.go, pkg/controllers/kepler.go, pkg/controllers/kepler_internal.go
This commit adds a `Degraded` status. When reconcile fails, the status
of the `available` condition is set to `Degraded`. The commit also fixes
the LastTransitionTime to reflect actual last changed time that that
latest time when any of the condition was updated.
=> feat: set availability to degraded when reconcile fails

go.mod, pkg/components/exporter/exporter.go, pkg/components/exporter/exporter_test.go, pkg/controllers/kepler_internal.go, pkg/reconciler/kepler.go
This commit modifies kepler reconciler to add the hash of redfish spec to pod annotations so that any change to the redfish spec will redeploy the pod.
This commit also fixes POWERMON-250 by removing the default redfish config added to kepler configmap.
=> POWERMON-251: ensure redfish config change restart kepler

.github/workflows/pr-checks.yaml, Makefile, hack/crds/prometheusrules.yaml, hack/crds/servicemonitors.yaml
Removing monitoring reduces the disk usage. 
Operator requires servicemonitor and prometheusrule crd for installing kepler thus these crds need to be added to the cluster.
=> ci: setup kind without monitoring

hack/uninstall-operator.sh
This PR updates the uninstall script for capturing the operator name. The previous method was not optimal and was prone to error in cases where the user uninstalled any previous operator using UI. `oc get operators` will still show the operator being present. 
For eg:
```
oc get subs -A ; oc get operators                                                           
NAMESPACE             NAME                             PACKAGE                          SOURCE             CHANNEL
openshift-operators   cluster-observability-operator   cluster-observability-operator   redhat-operators   development
NAME                                                 AGE
cluster-observability-operator.openshift-operators   59m
kepler-operator.openshift-operators                  27m …
```
=> fix: improve operator name capture in uninstall script

pkg/components/estimator/estimator.go, pkg/components/modelserver/modelserver.go, tests/images.yaml
Update stable image and test image for Kepler Model Server
Please refer to the release note: 
https://github.com/sustainable-computing-io/kepler-model-server/releases/tag/v0.7.7-release
Signed-off-by: Sunyanan Choochotkaew <sunyanan.choochotkaew1@ibm.com>
=> update kepler-model-server version to 0.7.7

pkg/components/exporter/exporter.go
This PR restricts visibility to only the power-monitoring-overview dashboard in the OpenShift developer console due to the
console's limitation on per-namespace visualization
=> fix: allow only overview dashboard to be visible inside OpenShift developer console

must-gather/gather
kepler doesnt use kprobes anymore, and bcc is removed.
Update `must-gather` to get ebpf related information from kepler nodes.
=> fix(must-gather): user bpftool to get ebpf related info

bundle/manifests/kepler-operator.clusterserviceversion.yaml, config/samples/kepler.system_v1alpha1_kepler.yaml, pkg/api/v1alpha1/kepler_types.go
Previously, when creating Kepler instance through OpenShift Console / UI, the redfish spec which is optional also had its fields initialized as well.  Notably `redfish.secrefRef` was initialized to "". This prevented creation of `kepler` instance since the `secretRef` is a required field.
This commit fixes the issue by marking `redfish` as `optional` and updating the default sample to reflect that.
=> fix(OLM): ensure kepler can be created through Console

pkg/components/exporter/assets/dashboards/power-monitoring-overview.json
This reverts commit 21d829821a012e6aa9f75845cf342f5e13b28beb.
=> feat(dashboard): show platform power source

pkg/components/exporter/exporter.go
Cgroup is still used. Only the metrics are not going to be exposed anymore.
=> fix(cgroup): enable cgroup without exposing cgroup_metrics

Makefile, bundle/manifests/kepler-operator.clusterserviceversion.yaml, tests/e2e/kepler_internal_test.go
This commit bumps up Kepler version to 0.7.11
=> chore: bump up Kepler to 0.7.11

hack/dashboard/assets/kepler/dashboard.json, pkg/components/exporter/assets/dashboards/power-monitoring-by-ns.json
This commit fixes the issue where the wrong Prometheus rule was referenced for displaying `OTHER Power Consumption(W) by Pods` in the dashboard
=> POWERMON-306: fix wrong Prometheus rule reference for OTHER Power Consumption

pkg/components/estimator/estimator.go, pkg/components/modelserver/modelserver.go, tests/images.yaml
This commit bumps up model-server image to `v0.7.11`
Address #412
=> chore: Bump up model-server to v0.7.11

.github/workflows/pr-checks.yaml, tests/run-e2e.sh
This commit adds a new workflow for running operator upgrade test separately from the existing e2e tests. The `run-e2e.sh` script is updated to run the operator upgrade scenario independently from the existing e2e tests. Additionally, the `pr-checks.yaml` workflow is modified to run the workflow before the e2e tests, ensuring that upgrade issues are identified early in the CI
Addresses #414
=> feat(ci): Add workflow for operator upgrade scenario

pkg/components/exporter/assets/dashboards/power-monitoring-by-ns.json
This commit removes the extra braces from the legend of the Power Monitoring by Namespace dashboard for the `OTHER Power Consumption by Pods` panel
=> fix(dashboard): remove extra braces from legend

pkg/components/estimator/estimator.go, pkg/components/estimator/estimator_test.go, pkg/components/exporter/exporter.go, pkg/components/modelserver/modelserver.go, pkg/components/modelserver/modelserver_test.go, tests/images.yaml
This commit bumps up model-server to `v0.7.11-2`
Addresses: #420
=> chore: Bump up model-server to v0.7.11-2

pkg/components/modelserver/modelserver.go
This commit addresses a permission issue where the model server, running as non-root user fails to create the resource directory under `/usr/local/lib/python3.10/site-packages/` A new volume and mount is added specifically for this ensuring necessary permissions are set
=> fix(modelserver): add volume mount for resource directory

Makefile, bundle/manifests/kepler-operator.clusterserviceversion.yaml
This commit bump up the Kepler version to 0.7.12
Addresses #432
=> feat: bump up Kepler to 0.7.12

hack/cluster.sh
This commit updates the `cluster.sh` to explicitly use a fixed OLM version, resolving issue where the `operator-sdk` defaults to the latest OLM version. The latest OLM version `v0.29.0` has an issue affecting pod deployments on KinD clusters causing failures
Ref: https://github.com/operator-framework/operator-lifecycle-manager/issues/3419
=> fix: specify olm version

.github/workflows/pr-checks.yaml, tests/run-e2e.sh
This commit removes the steps previously used to reclaim space on GH runners. Since we have moved to self-hosted runners with more resources available, these steps are no longer necessary
Addresses: #429
=> chore(ci): remove space reclamation steps for GH runners

hack/dashboard/openshift/deploy-grafana.sh, hack/dashboard/openshift/grafana-config/01-grafana-instance.yaml, hack/dashboard/openshift/grafana-config/03-grafana-datasource-UPDATETHIS.yaml, hack/dashboard/openshift/grafana-config/04-kepler-dashboard.yaml, hack/dashboard/openshift/grafana-config/05-prometheus-dashboard.yaml, hack/dashboard/openshift/grafana-deploy/01-grafana-operator.yaml, hack/dashboard/openshift/uwm/00-openshift-monitoring-user-projects.yaml
fix deploy-grafana.sh script to make it compatible with OCP 4.16  version. 
Following updates were made:
1. corrected document links
2. deploy-grafana.sh script updated to carry latest oc client version
3. added labels in grafana resource and updated grafana docker image to latest version
4. apiVersion updated for Grafana,GrafanaDatasource,GrafanaDashboard resource definitions
5. grafana-operator channel updated to latest version
6. other cosmetic changes
=> fix_deploy_grafana_script

hack/dashboard/assets/prometheus/dashboard.json
This commit resolves the issue where the dashboard failed to load due to hardcoded UID value. Instead of using a fixed UID the UID is now dynamically set to `${datasource}` Grafana variable.
=> fix(dashboard): replace hardcoded UID with datasource variable

tests/e2e/kepler_internal_test.go
This commit bumps up Kepler version used in internals e2e tests which was left in previous bump up commit #435
=> fix(tests): bump up kepler version in internals e2e

bundle/manifests/kepler-operator.clusterserviceversion.yaml, config/manifests/bases/kepler-operator.clusterserviceversion.yaml, hack/dashboard/openshift/deploy-grafana.sh, hack/dashboard/openshift/uwm/00-openshift-monitoring-user-projects.yaml
This PR updates the invalid links to the user workload monitoring to the new ones. The new links are moved from docs.openshift.com to docs.redhat.com as docs.openshift.com will be decommissioned soon.
=> docs: update deprecated UWM links

pkg/utils/test/assertions.go, pkg/utils/test/framework.go, tests/e2e/kepler_internal_test.go, tests/e2e/kepler_test.go
This commit updates the test framework to use wait.PollUntilContextTimeout instead of wait.PollImmediate, as the latter is deprecated.
=> chore(tests): use wait.PollUntilContextTimeout

Dockerfile, hack/dashboard/openshift/deploy-grafana.sh
This commit bumps up the oc cli version to 4.18
=> chore: bump up oc cli version

.github/codecov-upload/action.yaml
This commit fixes the issue where the wrong coverage file was being referenced in the codecov-upload action.
=> ci: use correct coverage file

.github/workflows/pr-checks.yaml, .github/workflows/publish-images.yaml, .github/workflows/release.yaml
Changes include:
* Use large runners for workflows (cuts down time)
* Run both upgrade and e2e tests in parallel
=> ci: improve workflow execution

Makefile, bundle/manifests/kepler-operator.clusterserviceversion.yaml, internal/config/config.go, internal/config/config_rapl_test.go, internal/config/config_test.go, internal/controller/config.go
This commit bumps up Kepler reboot version to v0.0.5
It also copy the config package from Kepler so that we can use the config available in Operator
=> chore: bump up kepler reboot

.github/workflows/pr-checks.yaml, Makefile
This commit removes `go fmt` and `go vet` dependencies from `make build`. It adds a go vet job to PR check workflow, matching go fmt setup. It also updates the build-bundle and build-images jobs to run without any dependencies.
=> ci: add dedicated go vet job to pr checks

.github/release.yml, .github/workflows/pr-checks.yaml, .github/workflows/publish-images.yaml, .github/workflows/release.yaml
This commit updates the existing release workflow.
Key changes:
- Workflow will now create a pull request with changes to bundle and
VERSION instead of directly committing to the repo.
- Update the action for creating a release
- Removed the job for creating a release branch
Note: For GH action to create pull request, we have to allow actions to create and approve pull requests under the repo settings
=> ci: update release workflow

.github/workflows/pr-checks.yaml, Makefile
This commit adds a check-changes job to the pr-check workflow which will check if any of the go files have been changed/added/removed. If any changes are detected, the workflow will run all the golang specific jobs (escape_detect, golangci, vulnerability_detect, codecov)
=> ci: run jobs based on file changes

.github/workflows/pr-checks.yaml
This commit adds the missing file check for the go vet job
=> ci: ensure go vet job also runs on file change

.github/workflows/pr-checks.yaml, tests/run-e2e.sh
This commit updates the e2e script to now accept commands to run the e2e tests. Now we can run e2e tests with the following commands:
```
./tests/run.sh upgrade-test
./test/run.sh e2e [args for e2e]
```
Addresses: #485
=> test: update e2e script to accept commands

.github/workflows/assign-labels.yaml
This commits adds a job which will label PRs based on conventional commit message standards.
=> ci: add job for labeling PR

.github/workflows/pr-checks.yaml
This commit adds the missing needs check in the golang based jobs.
=> ci: make sure golang based jobs depend on the check-changes job

must-gather/gather
This commit updates the must-gather script to also gather power-monitor related information. It refactors the existing gather script to include support for both Kepler and PowerMonitor making sure that the gather script is compatible with both instance types
=> chore: update must-gather to support power-monitor

bundle/metadata/annotations.yaml, hack/bundle.sh
This commit bumps up the supported ocp version for the operator to `4.16-4.19`
=> chore: bump up supported ocp version for the operator

hack/dashboard/openshift/grafana-config/01-grafana-instance.yaml, hack/dashboard/openshift/grafana-config/03-grafana-datasource-UPDATETHIS.yaml
When executing the script "./hack/dashboard/openshift/deploy-grafana.sh", we get following errors:
```
...
...
🔔 Creating a grafana instance
❯ oc apply -n kepler-grafana -f hack/dashboard/openshift/grafana-config/01-grafana-instance.yaml
The Grafana "kepler-grafana" is invalid:
* spec.config.auth.disable_signout_menu: Invalid value: "boolean": spec.config.auth.disable_signout_menu in body must be of type string: "boolean"
* spec.config.auth.anonymous.enabled: Invalid value: "boolean": spec.config.auth.anonymous.enabled in body must be of type string: "boolean"
* <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation
...
...
🔔 Creating datasource
❯ oc -n kepler-grafana create token …
```
=> Fix yaml error during the script run on "./hack/dashboard/openshift/deploy-grafana.sh"

pkg/components/power-monitor/assets/dashboards/power-monitor-node-info.json
This commit updates the cpu info panel to show the total number of cores. It also cleanup some of the unused/hidden fields from the panels
=> chore(dashboard): update cpu info panel to show total number of cores

tests/e2e/main_test.go, tests/e2e/power_monitor_internal_test.go, tests/e2e/power_monitor_test.go, tests/run-e2e.sh
Initially, enable_vm_test was populated using an enviornment variable. This was replaced with a command-line flag instead as it was more explicit.
=> tests(power-monitor): replace enable_vm_test env variable with command-line flag

tests/e2e/main_test.go
This commit makes use of the latest kepler release when running Power Monitor Internal tests
Addresses #508
=> test: use latest kepler release

.pre-commit-config.yaml
This commit ensures that the required precommit hooks are installed at the time of initial pre-commit setup
=> chore: ensure that required precommit hooks are installed

pkg/components/power-monitor/deployment.go
This commit removes the hard coded service monitor interval (15s) from the power-monitor
=> chore: remove service monitor interval from powermonitor

.github/workflows/pr-checks.yaml, .github/workflows/push.yaml, .github/workflows/test-and-codecov.yaml
This commit fixes the issue where the codecov calling workflow needs secret to be passed explicitly.
It also renames the publish-images workflow to push workflow for better clarity.
=> ci: specify codecov secret to the workflow

pkg/components/exporter/assets/dashboards/power-monitoring-by-ns.json, pkg/components/exporter/assets/dashboards/power-monitoring-overview.json
This commit updates the existing Kepler CR dashboards to include a new row which displays the Kepler CR deprecation notice.
It also moves all the existing panels to a separate collapsed row
=> chore: add Kepler CR deprecation notice to dashboards

.github/workflows/pr-checks.yaml, tests/e2e/kepler_internal_test.go, tests/e2e/kepler_test.go, tests/e2e/main_test.go
This commit ensures that only powermonitor tests are executed in the CI. It introduces `-skip-kepler-tests` flag that when set, skips all kepler tests
=> ci: ensure only powermonitor tests are executed

internal/controller/power_monitor_internal.go, pkg/components/power-monitor/assets/dashboards/power-monitor-namespace-info.json, pkg/components/power-monitor/assets/dashboards/power-monitor-node-info.json, pkg/components/power-monitor/deployment.go, pkg/components/power-monitor/deployment_test.go
This commit enhance the existing OpenShift dashboards. Changes include:
- Redesign the Power Monitor Info dashboard to now show:
- Current Node Power Consumption By Zone Stat
- Current Node Active Power Consumption By Zone Stat
- Current Node Idle Power Consumption By Zone Stat
- Node Active Power Consumption (W) By Zone Graph
- Node Idle Power Consumption (W) By Zone Graph
- Introduces a new dashboard to show namespace / pod related information which includes:
- Top 10 Power Consuming Namespaces (W) Table
- Total Power Consumption of Pods in Namespace (W) per Zone Graph
- Pod Power Consumption (W) By Zone Graph
=> chore: enhance OpenShift dashboards

.github/workflows/pr-checks.yaml, pkg/components/power-monitor/deployment.go, pkg/components/power-monitor/deployment_test.go, pkg/utils/test/framework.go, pkg/utils/test/power_monitor_internal_builder.go, tests/e2e/main_test.go, tests/e2e/power_monitor_internal_test.go, tests/e2e/power_monitor_test.go, tests/run-e2e.sh
This commit updates the e2e tests to now make use of additional config maps while setting up config to run fake cpu power meter on VM.
=> test: update the e2e to use config maps for VM test setup

pkg/components/power-monitor/assets/dashboards/power-monitor-namespace-info.json, pkg/components/power-monitor/assets/dashboards/power-monitor-overview.json, pkg/components/power-monitor/deployment.go, pkg/components/power-monitor/deployment_test.go
This commit updates the total power consumption panels to filter by zones. Now users can select the zones from the dropdown and the panel will filter the data accordingly.
Additional changes include:
- Rename the node-info dashboard to overview
- Introduces `All` option for the zone dropdown
- Disables the `Namespace Usage` row in the namespace info dashboard
- Renames the legend from `Total package-0 Watts` to `Zone - package-0` for better readability
=> chore: update total power consumption panels to filter by zone

pkg/components/power-monitor/assets/dashboards/power-monitor-overview.json
This commit updates the overview dashboard to use a table to show the current power consumptions instead of stats for better visibility.
It also removes the CPU Info panel from the dashboard.
=> chore(dashboard): use table to show current power consumption

Dockerfile, Makefile
This commit adds a new target to the Makefile to build the operator. `make build-manager` will only be responsible for building the operator `make build` will run the dependencies and build the operator.
It also updates the Dockerfile to use the build-manager target and pass on the required arguments to the build-manager.
=> chore: use build-manager target for building operator

Makefile
This commit updates the make target for building manager to remove hardcoded `CGO_ENABLED` value, enabling downstream builds to configure it for FIPS-compliant build
=> chore: allow CGO_ENABLED to be set during manager build

Makefile, bundle/manifests/kepler-operator.clusterserviceversion.yaml, internal/controller/config.go, tests/e2e/main_test.go
This commit bumps up the Kepler version to v0.0.10. There are no config changes for Kepler
=> chore: bump up Kepler version

.github/workflows/pr-checks.yaml, .pre-commit-config.yaml
This commit adds a custom hook for linting PR commits. It takes commit range from the PR and uses commitlint to lint the commits.
=> ci: use custom hook for linting PR commits

Makefile, bundle/manifests/kepler-operator.clusterserviceversion.yaml, config/samples/kepler.system_v1alpha1_powermonitor.yaml
This commit updates the log level for Kepler to be info instead of debug
=> chore: use log level as info for Kepler

must-gather/gather, must-gather/utils
This commit updates the must-gather script:
- Removes the older Kepler related steps
- Add a new step to capture RAPL information from power-monitor pods
=> chore: remove older Kepler related steps in must-gather

pkg/components/power-monitor/deployment.go, pkg/components/power-monitor/deployment_test.go, pkg/reconciler/power-monitor.go, pkg/reconciler/security.go
Renamed MountConfigMapToDaemonset and MountSecretAnnotationToDaemonset to AnnotateDaemonSetWithConfigMapHash and AnnotateDaemonSetWithSecretHash respectively to remove ambiguity.
=> chore: rename MountSecretAnnotationToDaemonset and MountConfigMapToDaemonSet

internal/controller/power_monitor_internal.go, pkg/reconciler/security.go
When cluster type is OpenShift, the timeout is changed to 60 seconds. When cluster type is K8s, the timeout is changed to 6 seconds.
=> chore: change timeout depending on cluster type

bundle/manifests/kepler-operator.clusterserviceversion.yaml, config/samples/kepler.system_v1alpha1_powermonitor.yaml, tests/run-e2e.sh
This commit updates the PowerMonitor CR example to include security settings with default values
=> chore: add example for security setting in PowerMonitor CR

pkg/components/power-monitor/deployment.go, pkg/components/power-monitor/deployment_test.go, pkg/reconciler/power-monitor.go, pkg/reconciler/security.go
For builders that can return an error  like KeplerConfig and NewPowerMonitorKubeRBACProxyConfig, errors from these functions are now returned to the reconcilers to be handled gracefully.
=> chore: add error propagation to deployment.go

codecov.yml
This commit ignores certain utils files which are related for e2e tests and not impact actual source code being ignored by codecov when generating the coverage report
=> ci: ignore utils from codecov generation

pkg/utils/test/framework.go, tests/e2e/main_test.go, tests/e2e/power_monitor_internal_test.go, tests/e2e/power_monitor_test.go
This commit updates the e2e test for RBAC ensuring that it can run on OpenShift. Existing e2e tests were specific to Kubernetes hence deploys prerequisites for OpenShift on Kubernetes like cert-manager certs, etc. which are not required when running tests against an OpenShift cluster.
In case of OpenShift, it creates the ConfigMap in `testNs` namespace with the annotation `service.beta.openshift.io/inject-cabundle": "true"` OpenShift automatically detects this annotation and injects the service CA certs leveraging OpenShift's automatic CA injection mechanism.
=> test: ensure RBAC e2e can run on OpenShift

.github/publish-images/action.yaml, .github/tools-cache/action.yaml, .github/workflows/pr-checks.yaml, .github/workflows/push.yaml, .github/workflows/release.yaml, Makefile
This commit updates the check-changes job to now also track Makefile ensuring that any changes to the Makefile targets that are used in the workflows are also validated.
This also updates the workflows to now use latest/specific version of GH actions used instead of `main` branch.
=> chore: track Makefile as part of check changes

tests/e2e/main_test.go
This commit replaces the variable argument for deployment-namespace from KeplerDeploymentNS to PowerMonitorDeploymentNS ensuring that correct variable stores the value of the flag
=> test: set the deployment-namespace to PowerMonitor ns

bundle/metadata/annotations.yaml, hack/bundle.sh
This commit updates the annotations to set the OCP version range from 4.17-4.19
=> chore: set OCP version range from OCP 4.17-4.19

tests/e2e/power_monitor_internal_test.go, tests/e2e/power_monitor_test.go, tests/utils/framework.go
This commit updates the PowerMonitor and Internal tests to wait for CR to be reconciled before creating any resources which depends on the CR to be created.
It also adds a check to wait for namespace to be deleted before deleting the CR
This prevents failures on OpenShift when CR creation/deletion is slow
=> test: wait for reconciliation before creating resources

tests/utils/framework.go
This commit ensures that tests wait for availability as false before creating additional config map which enables fake cpu meter when running on VM so that tests don't try to create configmap before CR is even created.
=> test: wait for availability as false before enabling fake cpu meter

Makefile, bundle/manifests/kepler-operator.clusterserviceversion.yaml, internal/config/config.go, internal/config/config_test.go, internal/config/redfish/config.go, internal/config/redfish/config_test.go, pkg/components/power-monitor/deployment.go, pkg/components/power-monitor/deployment_test.go, tests/e2e/main_test.go
This commit bumps up Kepler to v0.11.0.
Changes include:
- Bumping up Kepler to v0.11.0
- Move the latest config to internal/config/
- Skip validating external redfish config for controller manager
=> chore: bump up Kepler to v0.11.0

pkg/components/power-monitor/assets/dashboards/power-monitor-namespace-info.json
Removes the includeAll and multi-select options from namespace and pod template variables in the Power Monitor Namespace dashboard so that not all namespaces and pods are shown by default in the time series graphs
=> fix(powermonitor): remove All option from namespace and pod dropdowns

bundle/manifests/kepler-operator.clusterserviceversion.yaml, cmd/main.go, config/manager/overlays/openshift/kustomization.yaml, config/manifests/bases/kepler-operator.clusterserviceversion.yaml, internal/controller/config.go, internal/controller/power_monitor_internal.go, internal/controller/token_expiry.go, pkg/components/power-monitor/deployment.go, pkg/components/power-monitor/deployment_test.go, pkg/reconciler/power-monitor.go, pkg/reconciler/security.go, pkg/reconciler/security_test.go, pkg/reconciler/service_monitor.go, pkg/reconciler/service_monitor_test.go
Before this patch, the Prometheus User Workload Token Secret did not have a reliable reconciliation pattern to handle expirations. This patch added a controller which will remove any secrets that have expired, so they can be reconciled. The UWM Token Secret has its expiration date reduced from 1 year to 1 week, and the controller will check for expired tokens once per day.
=> feat: add secret expiration reconciler

must-gather/README.md
This commit improves the must-gather readme
=> docs: improve must-gather guide

.github/workflows/pr-checks.yaml, .github/workflows/push.yaml, README.md, bundle/manifests/kepler-operator.clusterserviceversion.yaml, config/manifests/bases/kepler-operator.clusterserviceversion.yaml
This commit updates the repo to use the main branch instead of the v1alpha1 branch.
=> chore: switch from v1alpha1 to main
